In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


### (Python list) vs (Numpy Arrays)

In [3]:
import time
#execution performance
size = 10_000_000  # 10 Million size data

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

#numpy arrays
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end-start} seconds")

python list time = 0.7989001274108887 seconds
numpy array time = 0.057739973068237305 seconds


In [4]:
#memory
import sys

print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"numpy array size = {np_arr.nbytes} bytes")

python list size = 800000560000000 bytes
numpy array size = 80000000 bytes


In [5]:
#create - from lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.shape, arr.dtype)

arr2 = np.array([1, 2, 3, 4, 5, "prime"])
print(arr2, type(arr2), arr2.shape, arr2.dtype)

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2D, arr2D.shape, arr2D.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,) int64
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,) <U21
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3) int64


In [6]:
#create
arr1 = np.zeros((2,3)) #prefill
print(arr1, arr1.shape)

arr2 = np.ones((5, )) #prefill
print(arr2, arr2.shape)

arr3 = np.full((3, 4), 100) #prefill with val
print(arr3, arr3.shape)

arr4 = np.eye(3) #identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(0, 11, 2) #range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 3) #evenly spaced arrays
print(arr6, arr6.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.   50.5 100. ] (3,)


In [7]:
# Properties
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr.shape) #dimensions = m * n
print(arr.size)  #tot els - 9
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


## Operations on arrays

In [8]:
#Reshaping

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2))
print(reshaped, reshaped.shape)

flattened = arr.flatten() #2D => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [9]:
#Indexing
arr = np.array([1, 2, 3, 4, 5]) #1D
print(arr[0])
print(arr[3])

arr1 = np.array([[1, 2, 3], [4, 5, 6]]) #2D
print(arr1[0][2])
print(arr1[1][1])

1
4
3
5


In [10]:
#Fancy Indexing
arr = np.array([1, 2, 3, 4, 5])
idx = [0, 1, 3]
print(arr[idx])

#Boolean Indexing
arr = np.array([6, 7, 8, 9, 10])
print(arr[arr > 7])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[1 2 4]
[ 8  9 10]
[ 6  8 10]
[7 9]


In [11]:
#Slicing
arr = np.array([1, 2, 3, 4, 5])

print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[:])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]


In [12]:
#Copy vs View
#-> pylist - copy
nums = [1, 2, 3, 4, 5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200
print(sub_list)
print(nums)

#-> nparr - view
arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3]
# sub_arr = arr[1:3].copy()
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]


### Numpy Data Type

In [13]:
# Data Type

arr = np.array([1, 2, 3.14, 4, "Prime"]) 
print(arr, arr.dtype)

arr1 = np.array([3 + 5j]) #complex
arr2 = np.array([2 + 3j])
print(arr1 + arr2)
print(arr1 - arr2)

arr = np.array(["Prime", {1,2,3}, 3.14]) #object
print(arr, arr.dtype)

['1' '2' '3.14' '4' 'Prime'] <U32
[5.+8.j]
[1.+2.j]
['Prime' {1, 2, 3} 3.14] object


### Multi-dimensional arrays & Axes


In [14]:
# Multi-dimensional arrays

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [15]:
#3D array

arr3D = np.array([[[1, 2], [3, 4], [5, 6]],[[7, 8], [9, 10], [11, 12]]]) # 2 x 3 x 2

print(arr3D, arr3D.shape)

#indexing
print(arr3D[1, 1, 0])

#slicing
print(arr3D[:, 0, :]) # first row from both layers
print(arr3D[:, :, 0]) # first col from both layers

arr3D[:, 0, :] = 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


### Vectorization, Brodcasting and Normaliztion

In [16]:
#vectorization

arr = np.array([1, 2, 3, 4, 5])
print(arr ** 2)
print(arr + 10)

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
print(arr1 + arr2)

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]


In [17]:
#broadcasting

arr = np.array([1, 2, 3, 4, 5])
print(arr + 5)

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print(arr1.shape)
print(arr2.shape)

print(arr1 + arr2)


[ 6  7  8  9 10]
(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [18]:
# vector Normalization

arr = np.array([[1, 2], [3, 4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

print(mean)
print(std_dev)


[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


### Mathematical Functions

In [19]:
#Mathematical fnx

# aggregation

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [20]:
#power fnx

arr = np.array([1, 2, 3, 4, 5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [21]:
#log

arr = np.array([1, 2, 3, 4, 5])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [22]:
#rounding

print(np.round(3.14))
print(np.round(3.89))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))


arr = np.array([1, 2, -8, 3, 4, -5, 2, -5])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

3.0
4.0
4.0
3.0
3.0
[-8 -5  1  2  3  4]
[-8 -5 -5  1  2  2  3  4]
[1 2 8 3 4 5 2 5]
